tags are irrelevant

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -65,13 +65,16 @@ script:
   - rm -f travis_wait*.log
   - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)  
   - ls
-  - if [[ ${#TRAVIS_TAG} -eq 0 ]]; 
-    then 
-      travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
-      check_fail ;
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed"; 
+      check_fail; 
       dump_logs; 
-      check_warnings ;
-    fi # --as-cran
+      check_warnings ;      
+      travis_terminate 1;
+    fi
   - ls
   - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
